name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --features=sync
      - name: Run tests
        env:
          MAX_BOT_API_ACCESS_TOKEN: ${{ secrets.MAX_BOT_API_ACCESS_TOKEN }}
        run: cargo test --verbose --features=sync
